
export const SET_SELECTED_SPORT = "SET_SELECTED_SPORT"

export const SET_SELECTED_LEAGUE = "SET_SELECTED_LEAGUE"
export const NEXT_LEAGUE = "NEXT_LEAGUE"
export const PREV_LEAGUE = "PREV_LEAGUE"

export const SET_SELECTED_LEVEL = "SET_SELECTED_LEVEL"
// export const SET_SPORTS = "SET_SPORTS"

export const SET_SPORT_LEAGUE_LEVEL = "SET_SPORT_LEAGUE_LEVEL"

export const TOGGLE_DROP_DOWN = "TOGGLE_DROP_DOWN"
export const HIDE_DROP_DOWN = "HIDE_DROP_DOWN"

export const TOGGLE_SELECTED_BADGE = "TOGGLE_SELECTED_BADGE"
export const HIDE_SELECTED_BADGE = "HIDE_SELECTED_BADGE"

export const SET_PLAYER = "SET_PLAYER"
export const UPDATE_PLAYER = "UPDATE_PLAYER"

export const SET_SEARCHED_PLAYERS = "SET_SEARCHED_PLAYERS"
export const CLEAR_SEARCHED_PLAYERS = "CLEAR_SEARCHED_PLAYERS"
